spring:
 datasource:
  url: jdbc:mysql://localhost:3306/minorProject1_jbdl43?createDatabaseIfNotExist=true
  username: root
  password: root1234
 jpa:
  hibernate.ddl-auto: create
  show-sql: true
  
server:
 port: 8080